version: 1.0.{build}

configuration:
- Release

environment:
  matrix:
  # - VS_VERSION: 14 2015
  #   VS_PLATFORM: win32
  - VS_VERSION: 14 2015
    VS_PLATFORM: x64
  # - VS_VERSION: 15 2017
  #   VS_PLATFORM: x64

before_build:
  - cmd: >- 
      git submodule update --init --recursive

      cd .\test
      
      mkdir build
      
      cd .\build

      cmake .. -G "Visual Studio %VS_VERSION%" -DCMAKE_GENERATOR_PLATFORM=%VS_PLATFORM% -Wno-dev


build_script:
  - cmake --build . --config %CONFIGURATION% -- -maxcpucount 

test_script:
  - cmake --build . --config %CONFIGURATION% --target RUN_TESTS
